# JHUDSL App Lab - Spring 2017

## Instructors

- Jeff Leek
- John Muschelli
- Sean Kross

## Course Description

Are you interested in building data apps to help save the world, start the next 
big business, or just to see if you can? We run a data app prototyping class 
for people interested in creating these apps. We partner with people at the 
university and around the community to generate app ideas that matter.

One of the principles of our approach is that _anyone_ can prototype an app. 
Our class starts with some tutorials on [Shiny](https://shiny.rstudio.com/) and [R](https://www.r-project.org/). While we have no formal pre-reqs for the class
you will have much more fun if you have the background equivalent to our 
Coursera classes: 

- [Data Scientist's Toolbox](https://www.coursera.org/learn/data-scientists-tools)
- [R Programming](https://www.coursera.org/learn/r-programming)
- [Building R packages](https://www.coursera.org/learn/r-packages)
- [Developing Data Products](https://www.coursera.org/learn/data-products)

We will mostly be able to support development with R and Shiny but would be 
pumped to accept people with other kinds of development background - we just 
might not be able to give a lot of technical assistance. 

To see some examples of apps we will be building check out our [gallery](http://jhudatascience.org/data_app_gallery.html).

### Meeting Times

- 4pm - 5pm EST Wednesday & Friday
- March 8th - May 19th
- No class on March 22 or 24

## [Code of Conduct](code-of-conduct.html)

## [Discussion Forums](https://www.reddit.com/r/jhudatascience/)

### Sign-up Instructions

1. Go to https://www.reddit.com/
2. In the upper right-hand corner click "sign up" to create an account if you
don't already have one.
3. Go to [our subreddit](https://www.reddit.com/r/jhudatascience/) and then
click "Message the Moderators." Tell us your name, email address, and JHED in
the message so we can give you access.

## Course Materials

| Week/Lecture  | Lecture  |  Video | Notes | Code |
|:------------|:------------|:------------|:------------|:------------|
| 1/1 | Welcome | [YouTube]() | [Google Slides](https://docs.google.com/presentation/d/1GmvPdhzf2SA3kUvxy1UDtucBPUXogWtQ5bUlKID5Nx0/edit?usp=sharing) | --- |
|1/2 | Some background tools | [Youtube]() | [Google Slides](https://docs.google.com/presentation/d/1s-z3FuEmIwgJfHCEr2wKKLXnetPHpxs8avRmmTL5hwo/edit?usp=sharing)| --- | 

## Resources For...

### Making Webpages

- [Make a simple static site](http://rmarkdown.rstudio.com/rmarkdown_websites.html)
- [Add carosels, tooltips, popovers](https://ijlyttle.github.io/bsplus/index.html)

### Building Shiny Apps

- [Have users sign in with Google](https://lesliemyint.wordpress.com/2017/01/01/creating-a-shiny-app-with-google-login/)
- [Send and receieve text messages](https://github.com/seankross/twilio)
- [Build a dashboard](http://lenkiefer.com/2017/01/22/build-flex)
- [Make your app HIPAA compliant by using Google services](https://static.googleusercontent.com/media/gsuite.google.com/en//terms/2015/1/hipaa_implementation_guide.pdf)
- [Take payments from credit and debit cards](https://github.com/MarkEdmondson1234/stripeR)
- [Show and hide elements, interface with Javascript](https://github.com/daattali/shinyjs)
- [Use Google Sheets to store and retrieve data](https://github.com/jennybc/googlesheets/tree/master/inst/shiny-examples)
- [Edit photos/images in a Shiny app](https://jfiksel.github.io/2017-02-26-cropping_images_with_a_shiny_app/)
- [40 small Shiny examples](http://zevross.com/blog/2016/04/19/r-powered-web-applications-with-shiny-a-tutorial-and-cheat-sheet-with-40-example-apps/)

### Developing R Packages

- [Writing an R package from scratch](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/)
- [Build an R package (Book Chapter)](https://bookdown.org/rdpeng/RProgDA/building-r-packages.html)

### Using Algorithms & Methods

- [Machine Learning](http://will-stanton.com/machine-learning-with-r-an-irresponsibly-fast-tutorial/)

### Reference Books

- [The Unix Workbench](http://seankross.com/the-unix-workbench/) - Basics of
Unix, the command line, Git and GitHub.
- [Developing Data Products](https://datasciencespecialization.github.io/Developing_Data_Products/) - Shiny app examples, interactive graphics, making maps.
- [Mastering Software Development in R](https://bookdown.org/rdpeng/RProgDA/) - R programming, building packages, making custom visualizations.
